import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tridsprojects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.thirteen}>
          <a
            href="https://www.dropbox.com/s/u11nzj7sj1a295k/BubbRTSv.023.rar?dl=0"
	    target="_blank"
          >
            <code className={styles.code}>BubbRTS v.023 available here</code>
          </a>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://www.dropbox.com/s/u11nzj7sj1a295k/BubbRTSv.023.rar?dl=0"
            className={styles.card}
            target="_blank"
          >
            <h2 className={inter.className}>
              BubbRTS <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             Newest version v0.23 released <code>10/03/2023 07:29am</code>
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
