import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tridsprojects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.videoWrapper}>
          <video autoPlay muted loop playsInline className={styles.backgroundVideo}>
            <source src={require('./videos/BubbPlanet.mp4')} type="video/mp4" />
          </video>
        </div>
        <div className={styles.spin}>
          <a
            href="BubbRTS/bubbRTSLanding"
          >
            <code className={styles.code}>BubbRTSMobile v.025-A available here</code>
          </a>
        </div>

        <div className={styles.center}>
        </div>

        <div className={styles.grid}>
		  <a
            href="https://www.dropbox.com/scl/fi/4no50v8c40x7g695dngss/Tridquest-Origins-Pre-Alpha-6.zip?rlkey=bi56qu2finxbgvl550bxmx24r&st=jwp4hyqr&dl=0"
            className={styles.card}
            target="_blank"
          >
            <h2 className={inter.className}>
              Tridquest Origins Pre Alpha 6 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             Started earliest development in July 2025. Out of Hiatus and in active development since May 2026. Newest update released <code>25/07/2026 01:08am</code>
            </p>
          </a>
			
          <a
            href="BubbRTS/bubbRTSLanding"
            className={styles.card}
          >
            <h2 className={inter.className}>
              BubbRTS <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             In development since November 2022, halted since April 2023. Newest version v0.25-A released <code>07/07/2026 04:04pm</code>
            </p>
          </a>

	      <a
            href="https://www.dropbox.com/s/hgeu8qfbbaf8bcb/TimeRunnerBuild.rar?dl=0"
            className={styles.card}
            target="_blank"
          >
            <h2 className={inter.className}>
              TimeRunner <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             Originally developed for Android Mid 2022, this project has since been abandoned.
            </p>
          </a>

	      <a
            href="https://www.dropbox.com/s/h0rc8wkfwtbbvn4/TridClicker.rar?dl=0"
            className={styles.card}
            target="_blank"
          >
            <h2 className={inter.className}>
              TridClicker <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             Originally developed for Android Mid/Late 2022, this project has since been abandoned.
            </p>
          </a>

           <Link href="/" passHref className={styles.card}>
                  <h2 className={inter.className}>
                      Return<span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>Return to main page</p>
           </Link>
        </div>
      </main>
    </>
  )
}
