import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/BubbRTS.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BubbRTS: Tridsprojects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className={styles.center}>
              <div className={styles.basicBorder}> 
                  <p>BubbRTS is a Real Time Strategy game being developed for PC.</p> <br/>
                  <p>In BubbRTS, you build a base, accumulate resources and survive waves of opponents, developing technology and your society to combat invasion.</p><br/>
                  <p>New updates are being posted every second Thursday night with a list of additions, check Friday for the new version.</p>
              </div> 
          </div>

        <div className={styles.grid}>
          <a
            href="https://www.dropbox.com/s/caoowi1yhwe6oo9/BubbRTSv.025.rar?dl=0"
            className={styles.card}
            target="_blank"
          >
            <h2 className={inter.className}>
              Download <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             Download the newest version v0.25 from Dropbox
            </p>
          </a>

	  <a
            href="../unityprojects"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Return to Projects <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Return to the current projects page.
            </p>
          </a>

	  <a
            href="../index"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Return to Main Page <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Return to the main page.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
